name: Deno CI/CD

on:
  push:
    branches: ["main", "fix-deno-deploy"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write # Needed for auth with Deno Deploy

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable-worker-options

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test # Only run deploy after tests pass
    # Run on push to main or fix-deno-deploy branch, not on PRs
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fix-deno-deploy')

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno Astro Adapter
        run: deno add npm:@deno/astro-adapter

      - name: Build site
        run: deno run -A --allow-scripts npm:astro build

      # List directory contents to debug the issue
      - name: List dist directory
        run: ls -la dist/

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "kumak-blog" # Your Deno Deploy project name
          entrypoint: "server/entry.mjs" # The entry file is in dist/server/entry.mjs
          root: "dist" # The root directory is already dist