name: Deno CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write # Needed for auth with Deno Deploy

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.41.0" # Use a newer version of Deno compatible with lockfile v4

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable-worker-options

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test # Only run deploy after tests pass
    # Only deploy on push to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.41.0" # Use a newer version of Deno compatible with lockfile v4

      - name: Build site
        run: deno run -A --unstable-worker-options npm:astro build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1.10.0
        with:
          project: "kumak-blog" # Your Deno Deploy project name
          entrypoint: "dist/server/entry.mjs" # This file is generated by "npm build"
          root: "dist" # SSR apps still output to the "dist" folder by default